name: Unity Build Pipeline

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to build'
        required: true
        type: choice
        options:
          - main
          - dev
          - stage
          - prod
        default: main

      platform:
        description: 'Select the build platform'
        required: true
        type: choice
        options:
          - Android
          - iOS
          - Windows
          - macOS
        default: Android

      build_type:
        description: 'Select the build type'
        required: true
        type: choice
        options:
          - Dev
          - Stage
          - Prod
          - Beta
        default: Dev

      architecture:
        description: 'Select the build architecture'
        required: true
        type: choice
        options:
          - x86
          - x64
          - ARM
        default: x86

      configuration:
        description: 'Select the build configuration'
        required: true
        type: choice
        options:
          - Debug
          - Release
        default: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the selected branch
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/Ankur-Capermint/BuildAutomation_Demo.git'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.branch }}

      # Install Unity using the latest stable version of the game-ci Unity setup action
      - name: Set up Unity
        uses: game-ci/unity-actions/setup@v2  # Use the correct action version 'v2'
        with:
          unityVersion: '6000.0.30f1'  # Specify the Unity version you are using

      # Activate Unity Personal License
      - name: Activate Unity Personal License
        run: |
          echo "Activating Unity Personal License..."
          unity-editor -batchmode -nographics -quit -logFile /dev/stdout \
          -serial "${{ secrets.UNITY_SERIAL_NUMBER }}" \
          -username "${{ secrets.UNITY_USERNAME }}" \
          -password "${{ secrets.UNITY_PASSWORD }}"

      # Build Unity project
      - name: Build Unity project
        run: |
          unity -batchmode -quit -projectPath ./ \
          -buildTarget ${{ github.event.inputs.platform }} \
          -customBuildTarget ${{ github.event.inputs.platform }} \
          -buildPath ./build_output \
          -configuration ${{ github.event.inputs.configuration }} \
          -architecture ${{ github.event.inputs.architecture }} \
          -buildName ${{ github.event.inputs.build_type }}
